#!/usr/bin/sh

# Script:       backlight
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      02-10-23
# Dependencies: acpilight, dunstify
#
# Copyright (C) 2023 Arkaprabha Chakraborty

# icon path
ICON_DIR=/usr/share/icons/Gruvbox-Material-Dark
BRIGHTNESS=$ICON_DIR/48x48/apps/display-brightness.svg

PROG=xbacklight
NOTIPROG=dunstify

case $1 in
-i)
  # Set the brightness on (if it was muted)
  if [ $($PROG -getf | awk '{print substr($1, 1, length($1)-2)}') -ge 10 ]; then
    $PROG -inc 10
  else
    $PROG -set 10
  fi
  ;;
-d)
  if [ $($PROG -getf | awk '{print substr($1, 1, length($1)-2)}') -le 10 ]; then
    $PROG -set 1
  elif [ $($PROG -getf | awk '{print substr($1, 1, length($1)-2)}') -le 20 ]; then
    $PROG -set 10
  else
    $PROG -dec 10
  fi
  ;;
esac

brightness=$($PROG -getf | awk '{print substr($1, 1, length($1)-2)}') # brightness value
$NOTIPROG -a "brictl" -u low -r "9997" -h int:value:"$brightness" -i $BRIGHTNESS "Brightness: ${brightness}%" -t 2000
