#!/usr/bin/sh

# Script:       backlight
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      02-10-23
# Dependencies: acpilight, dunstify
#
# Copyright (C) 2023 Arkaprabha Chakraborty

# Directory where the icon for brightness is located (replace ICON_PACK with the actual icon pack)
ICON_DIR=/usr/share/icons/ICON_PACK
# Path to the brightness icon
BRIGHTNESS=$ICON_DIR/48x48/apps/display-brightness.svg

# Program to control display brightness
PROG=xbacklight
# Notification program
NOTIPROG=dunstify

# Case statement to determine the action based on the argument passed to the script
case $1 in
-i)
  # Increase brightness by 10 or set to 10 if less than 10
  if [ $($PROG -getf | awk '{print substr($1, 1, length($1)-2)}') -ge 10 ]; then
    $PROG -inc 10
  else
    $PROG -set 10
  fi
  ;;
-d)
  # Decrease brightness by 10 based on current brightness level
  if [ $($PROG -getf | awk '{print substr($1, 1, length($1)-2)}') -le 10 ]; then
    $PROG -set 1
  elif [ $($PROG -getf | awk '{print substr($1, 1, length($1)-2)}') -le 20 ]; then
    $PROG -set 10
  else
    $PROG -dec 10
  fi
  ;;
esac

# Retrieve the current brightness value
brightness=$($PROG -getf | awk '{print substr($1, 1, length($1)-2)}')
# Send a notification displaying the current brightness level
$NOTIPROG -a "brictl" -u low -r "9997" -h int:value:"$brightness" -i $BRIGHTNESS "Brightness: ${brightness}%" -t 2000
