#!/usr/bin/sh

# Script:       battery
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      07-08-23
# Dependencies: dunstify
#
# Copyright (C) 2023 Arkaprabha Chakraborty

# Setting the program name used for notifications
PROG=dunstify

# Directory where icons are located (replace ICON_PACK with the actual icon pack)
ICON_DIR=/usr/share/icons/ICON_PACK

# Icon paths for different battery statuses
BATTERY_FULL=$ICON_DIR/48x48/status/battery-full.svg
BATTERY_LOW=$ICON_DIR/48x48/status/battery-low.svg
BATTERY_CAUTION=$ICON_DIR/48x48/status/battery-caution.svg
AC_ADAPTER=$ICON_DIR/48x48/status/ac-adapter.svg

# Thresholds for battery status
LOW=20
CRITICAL=10

# Initialize variables to track previous status and capacity
last_capacity=NONE
last_status=None

# Continuously monitor the battery status
while true; do
  # Path to battery information (replace BATTERY with the actual battery)
  BATTERY="/sys/class/power_supply/BATTERY"

  # Check if the battery path exists
  if [ -d $BATTERY ]; then
    # Read battery capacity and status
    capacity=$(cat $BATTERY/capacity)
    status=$(cat $BATTERY/status)

    # Handling status changes for charging/discharging
    if [ $last_status = "None" ]; then
      last_status=$status
    elif [ $last_status != "Discharging" ] && [ $status = "Discharging" ]; then
      $PROG "Power Unplugged" --replace 667 --icon $AC_ADAPTER --timeout 2000
      last_status=$status
    elif [ $last_status != "Charging" ] && [ $status = "Charging" ]; then
      $PROG "Power Plugged" --replace 667 --icon $AC_ADAPTER --timeout 2000
      last_status=$status
    fi

    # Handling different battery capacity scenarios
    if [ $last_capacity != "FULL" ] && [ $status = "Full" ]; then
      $PROG "Battery Full" --replace 666 --icon $BATTERY_FULL
      last_capacity="FULL"
    elif [ $last_capacity != "LOW" ] && [ $status = "Discharging" ] &&
      [ $capacity -le $LOW ] && [ $capacity -gt $CRITICAL ]; then
      $PROG "Battery Low: $capacity%" --replace 666 --icon $BATTERY_LOW
      last_capacity=LOW
    elif [ $status = "Discharging" ] && [ $capacity -le $CRITICAL ]; then
      $PROG --urgency critical "Battery Critical: $capacity%" --replace 666 --icon $BATTERY_CAUTION
      last_capacity=CRITICAL
    fi
  fi
  # Wait for 2 seconds before checking battery status again
  sleep 2
done
