#!/usr/bin/sh

# Script:       incognito
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      13-11-23
# Dependencies: librewolf
#
# Copyright (C) 2023 Arkaprabha Chakraborty

PROG=librewolf
FLAGS=--private-window

exec $PROG $FLAG
