#!/usr/bin/sh

# Script:       minecraft
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      27-09-23
# Dependencies: minecraft
#
# Copyright (C) 2023 Arkaprabha Chakraborty

exec java -jar $HOME/.minecraft/launcher/SKlauncher-3.1.2.jar
