#!/usr/bin/sh

# Script:       sbg
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      28-07-23
# Dependencies: feh, dunstify
#
# Copyright (C) 2023 Arkaprabha Chakraborty

PROG=feh           # program
NOTIPROG=dunstify  # program
FLAGS=--bg-fill    # program flags
WALL=$1            # original image
REST=$HOME/.bg     # duplicate image

cp "$WALL" "$REST"     # make a copy
"$PROG" "$FLAGS" "$REST" # set background
"$NOTIPROG" "Set as background" -a "$PROG" -u "low" -t "2000" -I "$WALL"
