#!/usr/bin/sh

# Script:       screen-saver
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      18-11-23
# Dependencies: mpv
#
# Copyright (C) 2023 Arkaprabha Chakraborty

COPY=cp
PROG=mpv
FLAGS='--loop=inf --fullscreen'
SAVER=$HOME/.ss
VID=$1

if [[ -e $VID ]]; then
  $COPY $VID $SAVER
  $PROG $FLAGS $VID
else
  $PROG $FLAGS $SAVER
fi
