#!/usr/bin/sh

# Script:       screen-saver
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      18-11-23
# Dependencies: mpv
#
# Copyright (C) 2023 Arkaprabha Chakraborty

PROG=mpv
FLAGS='--loop=inf --fullscreen'
VID=$1

$PROG $FLAGS $VID
