#!/usr/bin/sh

# Script:       screen-off
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      13-11-23
# Dependencies: xset
#
# Copyright (C) 2023 Arkaprabha Chakraborty

PROG=xset
FLAGS='dpms force off'

$PROG $FLAGS
