#!/usr/bin/sh

# Script:       screen-saver
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      18-11-23
# Dependencies: mpv
#
# Copyright (C) 2023 Arkaprabha Chakraborty

PROG=mpv
FLAGS="--fullscreen --loop=inf"
SAVER=$HOME/.ss
VID=$1

if [[ -e $VID ]]; then
  cp "$VID" "$SAVER"
  $PROG $FLAGS "$VID"
else
  $PROG $FLAGS "$SAVER"
fi
