#!/usr/bin/sh

# Script:       upcord
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      26-02-23
# Dependencies: curl, tar
#
# Copyright (C) 2023 Arkaprabha Chakraborty

if [ -d "/opt/Discord" ]; then
  sudo rm -rf /opt/Discord
fi

if [ -L "/bin/discord" ]; then
  sudo rm -f /bin/discord
fi

curl -Lfo "Discord.tar.gz" "https://discord.com/api/download?platform=linux&format=tar.gz"
tar xzvf Discord.tar.gz
sudo mv Discord /opt
sudo ln -s /opt/Discord/Discord /bin/discord
rm Discord.tar.gz
