#!/usr/bin/sh

# Script:       wal
# License:      MIT
# Author:       Arkaprabha Chakraborty
# Created:      28-07-23
# Dependencies: feh
#
# Copyright (C) 2023 Arkaprabha Chakraborty

PROG=feh         # program
FLAGS=--bg-fill  # program flags
WALL=$1          # original image
REST=$HOME/.wall # duplicate image

cp $WALL $REST     # make a copy
$PROG $FLAGS $REST # set background
